# Generated by Django 6.1 on 2026-08-18 22:33

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="название")),
                ("notes", models.TextField(blank=True, verbose_name="заметки")),
            ],
            options={
                "verbose_name": "предмет",
                "verbose_name_plural": "предметы",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Meter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="название")),
                (
                    "unit",
                    models.CharField(
                        help_text="км, литры, моточасы…",
                        max_length=50,
                        verbose_name="единица",
                    ),
                ),
                (
                    "expected_yearly_usage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Необязательно: «примерно 15 000 км в год».",
                        max_digits=12,
                        null=True,
                        verbose_name="ожидаемый годовой расход",
                    ),
                ),
                (
                    "reading_reminder_days",
                    models.PositiveIntegerField(
                        default=90,
                        verbose_name="напоминать ввести показания через, дней",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meters",
                        to="core.item",
                        verbose_name="предмет",
                    ),
                ),
            ],
            options={
                "verbose_name": "счётчик",
                "verbose_name_plural": "счётчики",
                "ordering": ["item", "name"],
            },
        ),
        migrations.CreateModel(
            name="MeterReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="значение"
                    ),
                ),
                (
                    "date",
                    models.DateField(default=datetime.date.today, verbose_name="дата"),
                ),
                (
                    "meter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="readings",
                        to="core.meter",
                        verbose_name="счётчик",
                    ),
                ),
            ],
            options={
                "verbose_name": "показание",
                "verbose_name_plural": "показания",
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="NotificationProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "telegram_chat_id",
                    models.CharField(
                        blank=True,
                        help_text="Заполнится при подключении бота.",
                        max_length=64,
                        verbose_name="Telegram chat id",
                    ),
                ),
                (
                    "quiet_hours_start",
                    models.TimeField(
                        default=datetime.time(22, 0), verbose_name="тихие часы с"
                    ),
                ),
                (
                    "quiet_hours_end",
                    models.TimeField(
                        default=datetime.time(9, 0), verbose_name="тихие часы до"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="учётка",
                    ),
                ),
            ],
            options={
                "verbose_name": "настройки уведомлений",
                "verbose_name_plural": "настройки уведомлений",
            },
        ),
        migrations.CreateModel(
            name="Obligation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="название")),
                ("notes", models.TextField(blank=True, verbose_name="заметки")),
                (
                    "rule_kind",
                    models.CharField(
                        choices=[
                            ("time", "по времени"),
                            ("meter", "по счётчику"),
                            ("both", "оба сразу — что раньше"),
                        ],
                        max_length=10,
                        verbose_name="вид правила срока",
                    ),
                ),
                (
                    "time_kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("once", "разово к дате"),
                            ("interval", "каждые N от последнего выполнения"),
                            ("annual", "ежегодно в фиксированную дату"),
                        ],
                        max_length=10,
                        verbose_name="правило по времени",
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="дата (для разового)"
                    ),
                ),
                (
                    "interval_value",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="интервал: сколько"
                    ),
                ),
                (
                    "interval_unit",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("days", "дней"),
                            ("weeks", "недель"),
                            ("months", "месяцев"),
                            ("years", "лет"),
                        ],
                        max_length=10,
                        verbose_name="интервал: чего",
                    ),
                ),
                (
                    "annual_month",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="ежегодно: месяц"
                    ),
                ),
                (
                    "annual_day",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="ежегодно: день"
                    ),
                ),
                (
                    "meter_interval",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Например, 8000 — каждые 8000 км.",
                        max_digits=12,
                        null=True,
                        verbose_name="интервал по счётчику",
                    ),
                ),
                (
                    "soon_threshold_percent",
                    models.PositiveSmallIntegerField(
                        default=70, verbose_name="порог «скоро», % интервала"
                    ),
                ),
                (
                    "overdue_repeat_days",
                    models.PositiveIntegerField(
                        default=7, verbose_name="повтор о просроченном, дней"
                    ),
                ),
                (
                    "is_private",
                    models.BooleanField(
                        default=False,
                        help_text="Личное видит только владелец, общее — вся семья.",
                        verbose_name="личное",
                    ),
                ),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_obligations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="исполнитель",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="obligations",
                        to="core.item",
                        verbose_name="предмет",
                    ),
                ),
                (
                    "meter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="obligations",
                        to="core.meter",
                        verbose_name="счётчик",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_obligations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="владелец",
                    ),
                ),
            ],
            options={
                "verbose_name": "обязательство",
                "verbose_name_plural": "обязательства",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Completion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(default=datetime.date.today, verbose_name="дата"),
                ),
                (
                    "meter_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="показание счётчика",
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="стоимость",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="заметка")),
                (
                    "done_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="completions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="кто сделал",
                    ),
                ),
                (
                    "obligation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completions",
                        to="core.obligation",
                        verbose_name="обязательство",
                    ),
                ),
            ],
            options={
                "verbose_name": "выполнение",
                "verbose_name_plural": "выполнения",
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="имя")),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="дата рождения"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="заметки")),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="person",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="учётка члена семьи",
                    ),
                ),
            ],
            options={
                "verbose_name": "человек",
                "verbose_name_plural": "люди",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="obligation",
            name="person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="obligations",
                to="core.person",
                verbose_name="человек",
            ),
        ),
        migrations.CreateModel(
            name="Fact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveBigIntegerField()),
                ("name", models.CharField(max_length=200, verbose_name="название")),
                (
                    "value",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="значение"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="facts/", verbose_name="файл"
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "строка фактуры",
                "verbose_name_plural": "фактура",
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="core_fact_content_828ca3_idx",
                    )
                ],
            },
        ),
    ]
