# Generated by Django 6.1 on 2026-08-19 18:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="obligation",
            name="created",
            field=models.DateField(
                default=datetime.date.today, editable=False, verbose_name="создано"
            ),
        ),
    ]
