# Generated by Django 6.1 on 2026-08-19 18:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_obligation_created"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("soon", "скоро срок"),
                            ("overdue", "просрочено"),
                            ("reading", "введите показания"),
                        ],
                        max_length=10,
                        verbose_name="вид",
                    ),
                ),
                ("text", models.TextField(verbose_name="текст")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="создано"
                    ),
                ),
                (
                    "not_before",
                    models.DateTimeField(
                        help_text="Отправка не раньше этого времени — конец тихих часов.",
                        verbose_name="не раньше",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "ожидает"), ("sent", "отправлено")],
                        default="pending",
                        max_length=10,
                        verbose_name="статус",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="отправлено"
                    ),
                ),
                (
                    "meter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="core.meter",
                        verbose_name="счётчик",
                    ),
                ),
                (
                    "obligation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="core.obligation",
                        verbose_name="обязательство",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="получатель",
                    ),
                ),
            ],
            options={
                "verbose_name": "уведомление",
                "verbose_name_plural": "уведомления",
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
