# Generated by Django 6.1 on 2026-08-22 16:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_notification"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="obligation",
            name="snoozed_until",
            field=models.DateField(
                blank=True,
                help_text="До этой даты напоминаний не будет — ставится кнопкой «Отложить» в Telegram. Пусто — напоминаем как обычно.",
                null=True,
                verbose_name="отложено до",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "ожидает"),
                    ("sent", "отправлено"),
                    ("stale", "устарело"),
                ],
                default="pending",
                max_length=10,
                verbose_name="статус",
            ),
        ),
        migrations.CreateModel(
            name="PendingInput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("cost", "стоимость выполнения"),
                            ("reading", "показание счётчика"),
                        ],
                        max_length=10,
                        verbose_name="что спросили",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="спрошено"
                    ),
                ),
                (
                    "completion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.completion",
                        verbose_name="выполнение",
                    ),
                ),
                (
                    "meter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.meter",
                        verbose_name="счётчик",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pending_input",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="кого спросили",
                    ),
                ),
            ],
            options={
                "verbose_name": "ожидание ответа",
                "verbose_name_plural": "ожидания ответа",
            },
        ),
    ]
