# Generated by Django 6.1 on 2026-08-22 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_telegram"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="название"
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=100,
                        help_text="Чем меньше, тем левее плашка.",
                        verbose_name="порядок",
                    ),
                ),
            ],
            options={
                "verbose_name": "раздел",
                "verbose_name_plural": "разделы",
                "ordering": ["order", "name"],
            },
        ),
        migrations.AddField(
            model_name="item",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items",
                to="core.category",
                verbose_name="раздел",
            ),
        ),
        migrations.AddField(
            model_name="obligation",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Пусто — берётся раздел предмета.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="obligations",
                to="core.category",
                verbose_name="раздел",
            ),
        ),
    ]
