# Generated by Django 6.1 on 2026-08-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_default_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="kind",
            field=models.CharField(
                choices=[
                    ("soon", "скоро срок"),
                    ("today", "срок сегодня"),
                    ("overdue", "просрочено"),
                    ("reading", "введите показания"),
                ],
                max_length=10,
                verbose_name="вид",
            ),
        ),
        migrations.AlterField(
            model_name="obligation",
            name="time_kind",
            field=models.CharField(
                blank=True,
                choices=[
                    ("once", "разово к дате"),
                    ("interval", "каждые N от последнего выполнения"),
                    ("annual", "ежегодно в фиксированную дату"),
                    ("someday", "когда получится — без срока"),
                ],
                max_length=10,
                verbose_name="правило по времени",
            ),
        ),
    ]
