# Generated by Django 6.1 on 2026-08-23 20:49
# Хвост дописан руками: разделам, заведённым до этой правки,
# значки проставляются по названию — иначе пользователю пришлось
# бы обходить справочник и выбирать их вручную.

from django.db import migrations, models

from core.значки import подобрать


def проставить(apps, schema_editor):
    """Уже заведённым разделам — значок по названию."""
    Category = apps.get_model("core", "Category")
    for раздел in Category.objects.all():
        значок = подобрать(раздел.name)
        if значок:
            раздел.icon = значок
            раздел.save(update_fields=["icon"])


def стереть(apps, schema_editor):
    """Откат: поле всё равно удаляется следом, чистить нечего."""


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_segodnya_i_bez_sroka"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="icon",
            field=models.CharField(
                blank=True,
                choices=[
                    ("машина", "машина"),
                    ("дом", "дом"),
                    ("участок", "участок"),
                    ("семья", "семья"),
                    ("деньги", "деньги"),
                    ("здоровье", "здоровье"),
                    ("учреждение", "учреждение"),
                    ("вещи", "вещи"),
                    ("животные", "животные"),
                    ("работа", "работа"),
                    ("учёба", "учёба"),
                    ("ремонт", "ремонт"),
                    ("поездки", "поездки"),
                    ("быт", "быт"),
                    ("техника", "техника"),
                    ("спорт", "спорт"),
                ],
                help_text="Картинка раздела в меню и на карточках. Необязательно.",
                max_length=20,
                verbose_name="значок",
            ),
        ),
        migrations.RunPython(проставить, стереть),
    ]
