# Generated by Django 6.1 on 2026-08-23 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_category_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="obligation",
            name="start_date",
            field=models.DateField(
                blank=True,
                help_text="День первого напоминания. Пусто — от дня заведения.",
                null=True,
                verbose_name="первый срок",
            ),
        ),
    ]
